package App;

import java.awt.Color;
import javax.swing.JFrame;
import javax.swing.JPanel;

public final class MainPage extends javax.swing.JFrame {

    private static Customer customer;
    private final PanelHome panelHome;
    private final PanelAccount panelAccount;
    private final PanelDeposit panelDeposit;
    private final PanelWithdraw panelWithdraw;
    private final PanelTranzactions panelTranzactions;
    private final PanelAdmin panelAdmin;

    /**
     * Creates new form Main_Page
     *
     * @param customer
     */

    public MainPage(Customer customer) {
        initComponents();
        this.setLocationRelativeTo(null);

        panelHome = new PanelHome();
        panelHome.setBounds(0, 0, 656, 661);

        panelAccount = new PanelAccount();
        panelAccount.setBounds(0, 0, 656, 661);

        panelDeposit = new PanelDeposit();
        panelDeposit.setBounds(0, 0, 656, 661);

        panelWithdraw = new PanelWithdraw();
        panelWithdraw.setBounds(0, 0, 656, 661);

        panelTranzactions = new PanelTranzactions();
        panelTranzactions.setBounds(0, 0, 656, 661);
        
        panelAdmin = new PanelAdmin();
        panelAdmin.setBounds(0, 0, 656, 661);

        mainContent.add(panelHome);
        mainContent.add(panelAccount);
        mainContent.add(panelDeposit);
        mainContent.add(panelWithdraw);
        mainContent.add(panelTranzactions);
        mainContent.add(panelAdmin);

        MainPage.customer = customer;

        menuClicked(panelHome);

        if (!customer.isAdmin()) {
            menu.remove(admin);
        }
    }

    public void menuClicked(JPanel choice) {
        panelHome.setVisible(false);
        panelAccount.setVisible(false);
        panelDeposit.setVisible(false);
        panelWithdraw.setVisible(false);
        panelTranzactions.setVisible(false);
        panelAdmin.setVisible(false);
        
        choice.setVisible(true);
    }

    /**
     * This method is called from within the constructor to initialize the form. WARNING: Do NOT modify this code. The content of this method is always regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        Border = new javax.swing.JPanel();
        minBtn = new javax.swing.JButton();
        exitBtn = new javax.swing.JButton();
        menu = new javax.swing.JPanel();
        logoOrName = new javax.swing.JLabel();
        account = new javax.swing.JPanel();
        toAccount = new javax.swing.JLabel();
        jLabel1 = new javax.swing.JLabel();
        jSeparator1 = new javax.swing.JSeparator();
        deposit = new javax.swing.JPanel();
        toDeposit = new javax.swing.JLabel();
        jLabel2 = new javax.swing.JLabel();
        jSeparator2 = new javax.swing.JSeparator();
        withdraw = new javax.swing.JPanel();
        toWithdraw = new javax.swing.JLabel();
        jLabel3 = new javax.swing.JLabel();
        jSeparator3 = new javax.swing.JSeparator();
        transaction = new javax.swing.JPanel();
        toTransaction1 = new javax.swing.JLabel();
        jLabel4 = new javax.swing.JLabel();
        jSeparator4 = new javax.swing.JSeparator();
        admin = new javax.swing.JPanel();
        toAdmin = new javax.swing.JLabel();
        jLabel5 = new javax.swing.JLabel();
        jSeparator5 = new javax.swing.JSeparator();
        mainContent = new javax.swing.JPanel();

        setDefaultCloseOperation(javax.swing.WindowConstants.EXIT_ON_CLOSE);
        setMinimumSize(new java.awt.Dimension(400, 300));
        setUndecorated(true);
        setResizable(false);

        Border.setBackground(new java.awt.Color(17, 11, 47));
        Border.setPreferredSize(new java.awt.Dimension(960, 720));

        minBtn.setBackground(new java.awt.Color(255, 255, 255));
        minBtn.setFont(new java.awt.Font("Berlin Sans FB", 0, 36)); // NOI18N
        minBtn.setForeground(new java.awt.Color(255, 255, 255));
        minBtn.setText("-");
        minBtn.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseEntered(java.awt.event.MouseEvent evt) {
                minBtnMouseEntered(evt);
            }
            public void mouseExited(java.awt.event.MouseEvent evt) {
                minBtnMouseExited(evt);
            }
        });
        minBtn.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                minBtnActionPerformed(evt);
            }
        });
        minBtn.addPropertyChangeListener(new java.beans.PropertyChangeListener() {
            public void propertyChange(java.beans.PropertyChangeEvent evt) {
                minBtnPropertyChange(evt);
            }
        });

        exitBtn.setBackground(new java.awt.Color(17, 11, 47));
        exitBtn.setFont(new java.awt.Font("Berlin Sans FB", 0, 28)); // NOI18N
        exitBtn.setForeground(new java.awt.Color(255, 255, 255));
        exitBtn.setText("X");
        exitBtn.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseEntered(java.awt.event.MouseEvent evt) {
                exitBtnMouseEntered(evt);
            }
            public void mouseExited(java.awt.event.MouseEvent evt) {
                exitBtnMouseExited(evt);
            }
        });
        exitBtn.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                exitBtnActionPerformed(evt);
            }
        });
        exitBtn.addPropertyChangeListener(new java.beans.PropertyChangeListener() {
            public void propertyChange(java.beans.PropertyChangeEvent evt) {
                exitBtnPropertyChange(evt);
            }
        });

        menu.setBackground(new java.awt.Color(255, 255, 255));
        menu.setPreferredSize(new java.awt.Dimension(300, 708));

        logoOrName.setBackground(new java.awt.Color(255, 255, 255));
        logoOrName.setHorizontalAlignment(javax.swing.SwingConstants.CENTER);
        logoOrName.setIcon(new javax.swing.ImageIcon(getClass().getResource("/src/bank.png"))); // NOI18N
        logoOrName.setOpaque(true);
        logoOrName.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                logoOrNameMouseClicked(evt);
            }
            public void mouseEntered(java.awt.event.MouseEvent evt) {
                logoOrNameMouseEntered(evt);
            }
            public void mouseExited(java.awt.event.MouseEvent evt) {
                logoOrNameMouseExited(evt);
            }
            public void mousePressed(java.awt.event.MouseEvent evt) {
                logoOrNameMousePressed(evt);
            }
            public void mouseReleased(java.awt.event.MouseEvent evt) {
                logoOrNameMouseReleased(evt);
            }
        });

        account.setBackground(new java.awt.Color(255, 255, 255));
        account.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                accountMouseClicked(evt);
            }
            public void mouseEntered(java.awt.event.MouseEvent evt) {
                accountMouseEntered(evt);
            }
            public void mouseExited(java.awt.event.MouseEvent evt) {
                accountMouseExited(evt);
            }
            public void mousePressed(java.awt.event.MouseEvent evt) {
                accountMousePressed(evt);
            }
            public void mouseReleased(java.awt.event.MouseEvent evt) {
                accountMouseReleased(evt);
            }
        });

        toAccount.setFont(new java.awt.Font("Berlin Sans FB", 0, 18)); // NOI18N
        toAccount.setForeground(new java.awt.Color(17, 11, 47));
        toAccount.setHorizontalAlignment(javax.swing.SwingConstants.CENTER);
        toAccount.setText("Fiók");
        toAccount.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                toAccountMouseClicked(evt);
            }
            public void mouseEntered(java.awt.event.MouseEvent evt) {
                toAccountMouseEntered(evt);
            }
            public void mousePressed(java.awt.event.MouseEvent evt) {
                toAccountMousePressed(evt);
            }
            public void mouseReleased(java.awt.event.MouseEvent evt) {
                toAccountMouseReleased(evt);
            }
        });

        jLabel1.setIcon(new javax.swing.ImageIcon(getClass().getResource("/src/account.png"))); // NOI18N
        jLabel1.setText("jLabel1");
        jLabel1.setMinimumSize(new java.awt.Dimension(512, 512));

        javax.swing.GroupLayout accountLayout = new javax.swing.GroupLayout(account);
        account.setLayout(accountLayout);
        accountLayout.setHorizontalGroup(
            accountLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING)
            .addGroup(accountLayout.createSequentialGroup()
                .addGroup(accountLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(accountLayout.createSequentialGroup()
                        .addGap(0, 40, Short.MAX_VALUE)
                        .addComponent(jLabel1, javax.swing.GroupLayout.PREFERRED_SIZE, 32, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                        .addComponent(toAccount, javax.swing.GroupLayout.PREFERRED_SIZE, 196, javax.swing.GroupLayout.PREFERRED_SIZE))
                    .addGroup(accountLayout.createSequentialGroup()
                        .addContainerGap()
                        .addComponent(jSeparator1)))
                .addContainerGap())
        );
        accountLayout.setVerticalGroup(
            accountLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(accountLayout.createSequentialGroup()
                .addContainerGap()
                .addGroup(accountLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(toAccount, javax.swing.GroupLayout.PREFERRED_SIZE, 32, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(jLabel1, javax.swing.GroupLayout.PREFERRED_SIZE, 32, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(jSeparator1, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(0, 0, Short.MAX_VALUE))
        );

        deposit.setBackground(new java.awt.Color(255, 255, 255));
        deposit.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                depositMouseClicked(evt);
            }
            public void mouseEntered(java.awt.event.MouseEvent evt) {
                depositMouseEntered(evt);
            }
            public void mouseExited(java.awt.event.MouseEvent evt) {
                depositMouseExited(evt);
            }
            public void mousePressed(java.awt.event.MouseEvent evt) {
                depositMousePressed(evt);
            }
            public void mouseReleased(java.awt.event.MouseEvent evt) {
                depositMouseReleased(evt);
            }
        });

        toDeposit.setFont(new java.awt.Font("Berlin Sans FB", 0, 18)); // NOI18N
        toDeposit.setForeground(new java.awt.Color(17, 11, 47));
        toDeposit.setHorizontalAlignment(javax.swing.SwingConstants.CENTER);
        toDeposit.setText("Befizetés");
        toDeposit.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                toDepositMouseClicked(evt);
            }
            public void mouseEntered(java.awt.event.MouseEvent evt) {
                toDepositMouseEntered(evt);
            }
            public void mousePressed(java.awt.event.MouseEvent evt) {
                toDepositMousePressed(evt);
            }
            public void mouseReleased(java.awt.event.MouseEvent evt) {
                toDepositMouseReleased(evt);
            }
        });

        jLabel2.setIcon(new javax.swing.ImageIcon(getClass().getResource("/src/deposit.png"))); // NOI18N
        jLabel2.setText("jLabel1");
        jLabel2.setMinimumSize(new java.awt.Dimension(512, 512));

        javax.swing.GroupLayout depositLayout = new javax.swing.GroupLayout(deposit);
        deposit.setLayout(depositLayout);
        depositLayout.setHorizontalGroup(
            depositLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(depositLayout.createSequentialGroup()
                .addGroup(depositLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(depositLayout.createSequentialGroup()
                        .addGap(0, 0, Short.MAX_VALUE)
                        .addComponent(jLabel2, javax.swing.GroupLayout.PREFERRED_SIZE, 32, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                        .addComponent(toDeposit, javax.swing.GroupLayout.PREFERRED_SIZE, 196, javax.swing.GroupLayout.PREFERRED_SIZE))
                    .addGroup(depositLayout.createSequentialGroup()
                        .addContainerGap()
                        .addComponent(jSeparator2)))
                .addContainerGap())
        );
        depositLayout.setVerticalGroup(
            depositLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(depositLayout.createSequentialGroup()
                .addGap(12, 12, 12)
                .addGroup(depositLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(toDeposit, javax.swing.GroupLayout.PREFERRED_SIZE, 30, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(jLabel2, javax.swing.GroupLayout.PREFERRED_SIZE, 32, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(jSeparator2, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(0, 0, Short.MAX_VALUE))
        );

        withdraw.setBackground(new java.awt.Color(255, 255, 255));
        withdraw.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                withdrawMouseClicked(evt);
            }
            public void mouseEntered(java.awt.event.MouseEvent evt) {
                withdrawMouseEntered(evt);
            }
            public void mouseExited(java.awt.event.MouseEvent evt) {
                withdrawMouseExited(evt);
            }
            public void mousePressed(java.awt.event.MouseEvent evt) {
                withdrawMousePressed(evt);
            }
            public void mouseReleased(java.awt.event.MouseEvent evt) {
                withdrawMouseReleased(evt);
            }
        });

        toWithdraw.setFont(new java.awt.Font("Berlin Sans FB", 0, 18)); // NOI18N
        toWithdraw.setForeground(new java.awt.Color(17, 11, 47));
        toWithdraw.setHorizontalAlignment(javax.swing.SwingConstants.CENTER);
        toWithdraw.setText("Kifizetés");
        toWithdraw.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                toWithdrawMouseClicked(evt);
            }
            public void mouseEntered(java.awt.event.MouseEvent evt) {
                toWithdrawMouseEntered(evt);
            }
            public void mousePressed(java.awt.event.MouseEvent evt) {
                toWithdrawMousePressed(evt);
            }
            public void mouseReleased(java.awt.event.MouseEvent evt) {
                toWithdrawMouseReleased(evt);
            }
        });

        jLabel3.setIcon(new javax.swing.ImageIcon(getClass().getResource("/src/withdraw.png"))); // NOI18N
        jLabel3.setText("jLabel1");
        jLabel3.setMinimumSize(new java.awt.Dimension(512, 512));

        javax.swing.GroupLayout withdrawLayout = new javax.swing.GroupLayout(withdraw);
        withdraw.setLayout(withdrawLayout);
        withdrawLayout.setHorizontalGroup(
            withdrawLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(withdrawLayout.createSequentialGroup()
                .addGroup(withdrawLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(withdrawLayout.createSequentialGroup()
                        .addGap(0, 0, Short.MAX_VALUE)
                        .addComponent(jLabel3, javax.swing.GroupLayout.PREFERRED_SIZE, 32, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                        .addComponent(toWithdraw, javax.swing.GroupLayout.PREFERRED_SIZE, 196, javax.swing.GroupLayout.PREFERRED_SIZE))
                    .addGroup(withdrawLayout.createSequentialGroup()
                        .addContainerGap()
                        .addComponent(jSeparator3)))
                .addContainerGap())
        );
        withdrawLayout.setVerticalGroup(
            withdrawLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(withdrawLayout.createSequentialGroup()
                .addGap(0, 12, Short.MAX_VALUE)
                .addGroup(withdrawLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(toWithdraw, javax.swing.GroupLayout.PREFERRED_SIZE, 30, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(jLabel3, javax.swing.GroupLayout.PREFERRED_SIZE, 32, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(jSeparator3, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(0, 0, 0))
        );

        transaction.setOpaque(false);

        toTransaction1.setFont(new java.awt.Font("Berlin Sans FB", 0, 18)); // NOI18N
        toTransaction1.setForeground(new java.awt.Color(17, 11, 47));
        toTransaction1.setHorizontalAlignment(javax.swing.SwingConstants.CENTER);
        toTransaction1.setText("Tranzakciók");
        toTransaction1.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                toTransaction1MouseClicked(evt);
            }
        });

        jLabel4.setIcon(new javax.swing.ImageIcon(getClass().getResource("/src/transaction.png"))); // NOI18N
        jLabel4.setMinimumSize(new java.awt.Dimension(512, 512));

        javax.swing.GroupLayout transactionLayout = new javax.swing.GroupLayout(transaction);
        transaction.setLayout(transactionLayout);
        transactionLayout.setHorizontalGroup(
            transactionLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, transactionLayout.createSequentialGroup()
                .addGroup(transactionLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING)
                    .addGroup(transactionLayout.createSequentialGroup()
                        .addContainerGap()
                        .addComponent(jSeparator4))
                    .addGroup(transactionLayout.createSequentialGroup()
                        .addGap(0, 34, Short.MAX_VALUE)
                        .addComponent(jLabel4, javax.swing.GroupLayout.PREFERRED_SIZE, 32, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                        .addComponent(toTransaction1, javax.swing.GroupLayout.PREFERRED_SIZE, 196, javax.swing.GroupLayout.PREFERRED_SIZE)))
                .addContainerGap())
        );
        transactionLayout.setVerticalGroup(
            transactionLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(transactionLayout.createSequentialGroup()
                .addGap(0, 12, Short.MAX_VALUE)
                .addGroup(transactionLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(toTransaction1, javax.swing.GroupLayout.PREFERRED_SIZE, 30, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(jLabel4, javax.swing.GroupLayout.PREFERRED_SIZE, 32, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(jSeparator4, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(8, 8, 8))
        );

        admin.setOpaque(false);

        toAdmin.setFont(new java.awt.Font("Berlin Sans FB", 0, 18)); // NOI18N
        toAdmin.setForeground(new java.awt.Color(17, 11, 47));
        toAdmin.setHorizontalAlignment(javax.swing.SwingConstants.CENTER);
        toAdmin.setText("Admin panel");
        toAdmin.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                toAdminMouseClicked(evt);
            }
        });

        jLabel5.setIcon(new javax.swing.ImageIcon(getClass().getResource("/src/admin.png"))); // NOI18N
        jLabel5.setText("jLabel1");
        jLabel5.setMinimumSize(new java.awt.Dimension(512, 512));

        javax.swing.GroupLayout adminLayout = new javax.swing.GroupLayout(admin);
        admin.setLayout(adminLayout);
        adminLayout.setHorizontalGroup(
            adminLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, adminLayout.createSequentialGroup()
                .addGroup(adminLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING)
                    .addGroup(adminLayout.createSequentialGroup()
                        .addContainerGap()
                        .addComponent(jSeparator5))
                    .addGroup(adminLayout.createSequentialGroup()
                        .addGap(0, 0, Short.MAX_VALUE)
                        .addComponent(jLabel5, javax.swing.GroupLayout.PREFERRED_SIZE, 32, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                        .addComponent(toAdmin, javax.swing.GroupLayout.PREFERRED_SIZE, 196, javax.swing.GroupLayout.PREFERRED_SIZE)))
                .addContainerGap())
        );
        adminLayout.setVerticalGroup(
            adminLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(adminLayout.createSequentialGroup()
                .addGap(0, 12, Short.MAX_VALUE)
                .addGroup(adminLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(toAdmin, javax.swing.GroupLayout.PREFERRED_SIZE, 30, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(jLabel5, javax.swing.GroupLayout.PREFERRED_SIZE, 32, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(jSeparator5, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(8, 8, 8))
        );

        javax.swing.GroupLayout menuLayout = new javax.swing.GroupLayout(menu);
        menu.setLayout(menuLayout);
        menuLayout.setHorizontalGroup(
            menuLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(account, javax.swing.GroupLayout.Alignment.TRAILING, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
            .addComponent(deposit, javax.swing.GroupLayout.Alignment.TRAILING, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
            .addComponent(withdraw, javax.swing.GroupLayout.Alignment.TRAILING, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
            .addComponent(transaction, javax.swing.GroupLayout.Alignment.TRAILING, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
            .addComponent(logoOrName, javax.swing.GroupLayout.Alignment.TRAILING, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
            .addComponent(admin, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
        );
        menuLayout.setVerticalGroup(
            menuLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, menuLayout.createSequentialGroup()
                .addGap(6, 6, 6)
                .addComponent(logoOrName, javax.swing.GroupLayout.PREFERRED_SIZE, 150, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                .addComponent(account, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(deposit, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(withdraw, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(0, 0, 0)
                .addComponent(transaction, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, 248, Short.MAX_VALUE)
                .addComponent(admin, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(0, 0, 0))
        );

        mainContent.setBackground(new java.awt.Color(255, 255, 255));
        mainContent.setOpaque(false);

        javax.swing.GroupLayout mainContentLayout = new javax.swing.GroupLayout(mainContent);
        mainContent.setLayout(mainContentLayout);
        mainContentLayout.setHorizontalGroup(
            mainContentLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGap(0, 656, Short.MAX_VALUE)
        );
        mainContentLayout.setVerticalGroup(
            mainContentLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGap(0, 0, Short.MAX_VALUE)
        );

        javax.swing.GroupLayout BorderLayout = new javax.swing.GroupLayout(Border);
        Border.setLayout(BorderLayout);
        BorderLayout.setHorizontalGroup(
            BorderLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(BorderLayout.createSequentialGroup()
                .addGap(6, 6, 6)
                .addComponent(menu, javax.swing.GroupLayout.PREFERRED_SIZE, 286, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addGroup(BorderLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING)
                    .addComponent(mainContent, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addGroup(BorderLayout.createSequentialGroup()
                        .addComponent(minBtn)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                        .addComponent(exitBtn, javax.swing.GroupLayout.PREFERRED_SIZE, 50, javax.swing.GroupLayout.PREFERRED_SIZE)))
                .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
        );
        BorderLayout.setVerticalGroup(
            BorderLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(BorderLayout.createSequentialGroup()
                .addGap(6, 6, 6)
                .addGroup(BorderLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addComponent(menu, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                    .addGroup(BorderLayout.createSequentialGroup()
                        .addGroup(BorderLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING, false)
                            .addComponent(exitBtn)
                            .addComponent(minBtn, javax.swing.GroupLayout.PREFERRED_SIZE, 42, javax.swing.GroupLayout.PREFERRED_SIZE))
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                        .addComponent(mainContent, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)))
                .addContainerGap())
        );

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(getContentPane());
        getContentPane().setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(Border, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(Border, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
        );

        pack();
    }// </editor-fold>//GEN-END:initComponents

    private void minBtnActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_minBtnActionPerformed
        this.setState(JFrame.ICONIFIED);
    }//GEN-LAST:event_minBtnActionPerformed

    private void minBtnPropertyChange(java.beans.PropertyChangeEvent evt) {//GEN-FIRST:event_minBtnPropertyChange
        minBtn.setOpaque(false);
        minBtn.setContentAreaFilled(false);
        minBtn.setBorderPainted(false);
    }//GEN-LAST:event_minBtnPropertyChange

    private void exitBtnActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_exitBtnActionPerformed
        System.exit(0);
    }//GEN-LAST:event_exitBtnActionPerformed

    private void exitBtnPropertyChange(java.beans.PropertyChangeEvent evt) {//GEN-FIRST:event_exitBtnPropertyChange
        exitBtn.setOpaque(false);
        exitBtn.setContentAreaFilled(false);
        exitBtn.setBorderPainted(false);
    }//GEN-LAST:event_exitBtnPropertyChange

    private void toAccountMouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_toAccountMouseClicked
        menuClicked(panelAccount);
    }//GEN-LAST:event_toAccountMouseClicked

    private void logoOrNameMouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_logoOrNameMouseClicked
        menuClicked(panelHome);
    }//GEN-LAST:event_logoOrNameMouseClicked

    private void toDepositMouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_toDepositMouseClicked
        menuClicked(panelDeposit);
    }//GEN-LAST:event_toDepositMouseClicked

    private void toWithdrawMouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_toWithdrawMouseClicked
        menuClicked(panelWithdraw);
    }//GEN-LAST:event_toWithdrawMouseClicked

    private void toTransaction1MouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_toTransaction1MouseClicked
        menuClicked(panelTranzactions);
    }//GEN-LAST:event_toTransaction1MouseClicked

    private void accountMouseEntered(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_accountMouseEntered
        account.setBackground(new Color(211, 211, 211));
    }//GEN-LAST:event_accountMouseEntered

    private void accountMouseExited(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_accountMouseExited
        account.setBackground(Color.WHITE);
    }//GEN-LAST:event_accountMouseExited

    private void toAccountMouseEntered(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_toAccountMouseEntered
        account.setBackground(new Color(211, 211, 211));
    }//GEN-LAST:event_toAccountMouseEntered

    private void toAccountMouseReleased(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_toAccountMouseReleased
        account.setBackground(Color.WHITE);
    }//GEN-LAST:event_toAccountMouseReleased

    private void minBtnMouseEntered(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_minBtnMouseEntered
        minBtn.setForeground(new Color(105, 105, 105));
    }//GEN-LAST:event_minBtnMouseEntered

    private void minBtnMouseExited(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_minBtnMouseExited
        minBtn.setForeground(Color.WHITE);
    }//GEN-LAST:event_minBtnMouseExited

    private void exitBtnMouseEntered(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_exitBtnMouseEntered
        exitBtn.setForeground(Color.red);
    }//GEN-LAST:event_exitBtnMouseEntered

    private void exitBtnMouseExited(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_exitBtnMouseExited
        exitBtn.setForeground(Color.WHITE);
    }//GEN-LAST:event_exitBtnMouseExited

    private void accountMousePressed(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_accountMousePressed
        account.setBackground(new Color(105, 105, 105));
    }//GEN-LAST:event_accountMousePressed

    private void toAccountMousePressed(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_toAccountMousePressed
        account.setBackground(new Color(105, 105, 105));
    }//GEN-LAST:event_toAccountMousePressed

    private void accountMouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_accountMouseClicked
        menuClicked(panelAccount);
    }//GEN-LAST:event_accountMouseClicked

    private void accountMouseReleased(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_accountMouseReleased
        account.setBackground(Color.WHITE);
    }//GEN-LAST:event_accountMouseReleased

    private void logoOrNameMousePressed(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_logoOrNameMousePressed
        logoOrName.setBackground(new Color(105, 105, 105));
    }//GEN-LAST:event_logoOrNameMousePressed

    private void logoOrNameMouseReleased(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_logoOrNameMouseReleased
        logoOrName.setBackground(new Color(211, 211, 211));
    }//GEN-LAST:event_logoOrNameMouseReleased

    private void logoOrNameMouseEntered(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_logoOrNameMouseEntered
        logoOrName.setBackground(new Color(211, 211, 211));
    }//GEN-LAST:event_logoOrNameMouseEntered

    private void logoOrNameMouseExited(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_logoOrNameMouseExited
        logoOrName.setBackground(Color.WHITE);
    }//GEN-LAST:event_logoOrNameMouseExited

    private void toDepositMouseEntered(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_toDepositMouseEntered
        deposit.setBackground(new Color(211, 211, 211));
    }//GEN-LAST:event_toDepositMouseEntered

    private void toDepositMousePressed(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_toDepositMousePressed
        deposit.setBackground(new Color(105, 105, 105));
    }//GEN-LAST:event_toDepositMousePressed

    private void toDepositMouseReleased(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_toDepositMouseReleased
        deposit.setBackground(new Color(211, 211, 211));
    }//GEN-LAST:event_toDepositMouseReleased

    private void depositMouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_depositMouseClicked
        menuClicked(panelDeposit);
    }//GEN-LAST:event_depositMouseClicked

    private void depositMouseEntered(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_depositMouseEntered
        deposit.setBackground(new Color(211, 211, 211));
    }//GEN-LAST:event_depositMouseEntered

    private void depositMouseExited(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_depositMouseExited
        deposit.setBackground(Color.WHITE);
    }//GEN-LAST:event_depositMouseExited

    private void depositMousePressed(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_depositMousePressed
        deposit.setBackground(new Color(105, 105, 105));
    }//GEN-LAST:event_depositMousePressed

    private void depositMouseReleased(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_depositMouseReleased
        deposit.setBackground(new Color(211, 211, 211));
    }//GEN-LAST:event_depositMouseReleased

    private void toWithdrawMouseEntered(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_toWithdrawMouseEntered
        withdraw.setBackground(new Color(211, 211, 211));
    }//GEN-LAST:event_toWithdrawMouseEntered

    private void toWithdrawMousePressed(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_toWithdrawMousePressed
        withdraw.setBackground(new Color(105, 105, 105));
    }//GEN-LAST:event_toWithdrawMousePressed

    private void toWithdrawMouseReleased(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_toWithdrawMouseReleased
        withdraw.setBackground(new Color(211, 211, 211));
    }//GEN-LAST:event_toWithdrawMouseReleased

    private void withdrawMouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_withdrawMouseClicked
        menuClicked(withdraw);
    }//GEN-LAST:event_withdrawMouseClicked

    private void withdrawMouseEntered(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_withdrawMouseEntered
        withdraw.setBackground(new Color(211, 211, 211));
    }//GEN-LAST:event_withdrawMouseEntered

    private void withdrawMouseExited(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_withdrawMouseExited
        withdraw.setBackground(Color.WHITE);
    }//GEN-LAST:event_withdrawMouseExited

    private void withdrawMousePressed(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_withdrawMousePressed
        withdraw.setBackground(new Color(105, 105, 105));
    }//GEN-LAST:event_withdrawMousePressed

    private void withdrawMouseReleased(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_withdrawMouseReleased
        withdraw.setBackground(new Color(211, 211, 211));
    }//GEN-LAST:event_withdrawMouseReleased

    private void toAdminMouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_toAdminMouseClicked
        menuClicked(panelAdmin);
    }//GEN-LAST:event_toAdminMouseClicked

    /**
     * @param args the command line arguments
     */
    public static void main(String args[]) {
        /* Set the Nimbus look and feel */
        //<editor-fold defaultstate="collapsed" desc=" Look and feel setting code (optional) ">
        /* If Nimbus (introduced in Java SE 6) is not available, stay with the default look and feel.
         * For details see http://download.oracle.com/javase/tutorial/uiswing/lookandfeel/plaf.html 
         */
        try {
            for (javax.swing.UIManager.LookAndFeelInfo info : javax.swing.UIManager.getInstalledLookAndFeels()) {
                if ("Nimbus".equals(info.getName())) {
                    javax.swing.UIManager.setLookAndFeel(info.getClassName());
                    break;
                }
            }
        } catch (ClassNotFoundException ex) {
            java.util.logging.Logger.getLogger(MainPage.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (InstantiationException ex) {
            java.util.logging.Logger.getLogger(MainPage.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (IllegalAccessException ex) {
            java.util.logging.Logger.getLogger(MainPage.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (javax.swing.UnsupportedLookAndFeelException ex) {
            java.util.logging.Logger.getLogger(MainPage.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        }
        //</editor-fold>
        //</editor-fold>

        /* Create and display the form */
        java.awt.EventQueue.invokeLater(new Runnable() {
            @Override
            public void run() {
                new MainPage(customer).setVisible(true);
            }
        });
    }

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JPanel Border;
    private javax.swing.JPanel account;
    private javax.swing.JPanel admin;
    private javax.swing.JPanel deposit;
    private javax.swing.JButton exitBtn;
    private javax.swing.JLabel jLabel1;
    private javax.swing.JLabel jLabel2;
    private javax.swing.JLabel jLabel3;
    private javax.swing.JLabel jLabel4;
    private javax.swing.JLabel jLabel5;
    private javax.swing.JSeparator jSeparator1;
    private javax.swing.JSeparator jSeparator2;
    private javax.swing.JSeparator jSeparator3;
    private javax.swing.JSeparator jSeparator4;
    private javax.swing.JSeparator jSeparator5;
    private javax.swing.JLabel logoOrName;
    private javax.swing.JPanel mainContent;
    private javax.swing.JPanel menu;
    private javax.swing.JButton minBtn;
    private javax.swing.JLabel toAccount;
    private javax.swing.JLabel toAdmin;
    private javax.swing.JLabel toDeposit;
    private javax.swing.JLabel toTransaction1;
    private javax.swing.JLabel toWithdraw;
    private javax.swing.JPanel transaction;
    private javax.swing.JPanel withdraw;
    // End of variables declaration//GEN-END:variables

}
